from rss_vms_installer.installer import RssVmsInstaller
from rss_vms_installer.open_jdk_java_8_installer import OpenJdkJava8Installer
from rss_vms_installer.utf_8_ru_locale_installer import Utf8RuLocaleInstaller
from rss_vms_installer.postgres_11_installer import Postgres11Installer
