from rss_vms_installer.installer import RssVmsInstaller
from rss_vms_installer.open_jdk_java_8_installer import OpenJdkJava8Installer
from rss_vms_installer.utf_8_ru_locale_installer import Utf8RuLocaleInstaller
from rss_vms_installer.postgres_11_installer import Postgres11Installer
from rss_vms_installer.postgis_2_5_installer import PostGIS25Installer
from rss_vms_installer.tomcat_8_5_23_installer import Tomcat8523Installer
from rss_vms_installer.tomcat_tuner import TomcatTuner
from rss_vms_installer.server_part_installer import ServerPartInstaller
from rss_vms_installer.logger_installer import LoggerInstaller
from rss_vms_installer.database_creator import DatabaseCreator
from rss_vms_installer.postgis_on_db_installer import PostgisOnDbInstaller
from rss_vms_installer.post_scripts_installer import PostScriptsInstaller

